on:
    push:
        branches:
            - master
  
name: Contributes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run update script
        run: node .github/scripts/update-readme.js
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README" -a || echo "No changes to commit"
          git push